/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpaneltests;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.List;

/**
 *
 * @author Paulo.Tenorio
 */
public class Test extends javax.swing.JPanel {
    public List< Integer > xPaintList;
    public List< Integer > yPaintList;
    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }
    
    @Override
    public void paint(java.awt.Graphics g)
    {
        super.paint(g);
        BufferedImage img = new BufferedImage(this.getSize().width,this.getSize().height,BufferedImage.TYPE_INT_ARGB);
        
        for (int i=0;i<xPaintList.size()&&i<yPaintList.size();i++)
        {
            int xvalue = xPaintList.get(i);
            int yvalue = yPaintList.get(i);
            
            img.setRGB(xvalue, yvalue, Color.PINK.getRGB());
        }
        
        g.drawImage(img,0,0,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
